export default function Modplayer(): void;
export default class Modplayer {
    supportedformats: string[];
    url: string;
    format: string;
    state: string;
    loading: boolean;
    playing: boolean;
    paused: boolean;
    repeat: boolean;
    separation: number;
    mixval: number;
    amiga500: boolean;
    filter: boolean;
    endofsong: boolean;
    autostart: boolean;
    bufferstodelay: number;
    delayfirst: number;
    onReady: () => void;
    onPlay: () => void;
    onStop: () => void;
    buffer: number;
    mixerNode: number;
    context: any;
    samplerate: number;
    bufferlen: number;
    chvu: Float32Array;
    player: Protracker | Screamtracker | Fasttracker | null;
    title: string;
    signature: string;
    songlen: number;
    channels: number;
    patterns: number;
    samplenames: any[];
    load(url: any): boolean;
    play(): boolean;
    pause(): void;
    stop(): void;
    stopaudio(st: any): void;
    jump(step: any): void;
    position: number | undefined;
    row: number | undefined;
    setrepeat(rep: any): void;
    setseparation(sep: any): void;
    setautostart(st: any): void;
    setamigamodel(amiga: any): void;
    setfilter(f: any): void;
    hassyncevents(): boolean;
    popsyncevent(): any;
    currentpattern(): any;
    patterndata(pn: any): Uint8Array | undefined;
    noteon(ch: any): any;
    currentsample(ch: any): any;
    currentpattlen(): any;
    createContext(): void;
    filterNode: any;
    lowpassNode: any;
    mix(ape: any): void;
}
import Protracker from "../players/pt";
import Screamtracker from "../players/st3";
import Fasttracker from "../players/ft2";
