export default function Fasttracker(): void;
export default class Fasttracker {
    onNextRow: () => void;
    playing: boolean;
    paused: boolean;
    repeat: boolean;
    filter: boolean;
    syncqueue: any[];
    samplerate: number;
    ramplen: number;
    mixval: number;
    periodtable: Float32Array;
    pan: Float32Array;
    finalpan: Float32Array;
    vibratotable: Float32Array[];
    voleffects_t0: ((mod: any, ch: any, data: any) => void)[];
    voleffects_t1: ((mod: any, ch: any, data: any) => void)[];
    effects_t0: ((mod: any, ch: any) => void)[];
    effects_t0_e: ((mod: any, ch: any) => void)[];
    effects_t1: ((mod: any, ch: any) => void)[];
    effects_t1_e: ((mod: any, ch: any) => void)[];
    clearsong(): void;
    title: string | undefined;
    signature: string | undefined;
    trackerversion: number | undefined;
    songlen: number | undefined;
    repeatpos: number | undefined;
    channels: number | undefined;
    patterns: number | undefined;
    instruments: number | undefined;
    amigaperiods: number | undefined;
    initSpeed: number | undefined;
    initBPM: number | undefined;
    patterntable: ArrayBuffer | undefined;
    pattern: any[] | undefined;
    instrument: any[] | undefined;
    chvu: Float32Array | undefined;
    initialize(): void;
    tick: number | undefined;
    position: number | undefined;
    row: number | undefined;
    flags: number | undefined;
    volume: number | undefined;
    speed: number | undefined;
    bpm: number | undefined;
    stt: number | undefined;
    breakrow: number | undefined;
    patternjump: number | undefined;
    patterndelay: number | undefined;
    patternwait: number | undefined;
    endofsong: boolean | undefined;
    looprow: number | undefined;
    loopstart: number | undefined;
    loopcount: number | undefined;
    globalvolslide: number | undefined;
    channel: any[] | undefined;
    parse(buffer: any): boolean;
    patternlen: any[] | undefined;
    calcperiod(mod: any, note: any, finetune: any): number;
    advance(mod: any): void;
    process_note(mod: any, p: any, ch: any): void;
    process_tick(mod: any): void;
    mix(mod: any, bufs: any, buflen: any): void;
    effect_vol_t0_60(mod: any, ch: any, data: any): void;
    effect_vol_t0_70(mod: any, ch: any, data: any): void;
    effect_vol_t0_80(mod: any, ch: any, data: any): void;
    effect_vol_t0_90(mod: any, ch: any, data: any): void;
    effect_vol_t0_a0(mod: any, ch: any, data: any): void;
    effect_vol_t0_b0(mod: any, ch: any, data: any): void;
    effect_vol_t0_c0(mod: any, ch: any, data: any): void;
    effect_vol_t0_d0(mod: any, ch: any, data: any): void;
    effect_vol_t0_e0(mod: any, ch: any, data: any): void;
    effect_vol_t0_f0(mod: any, ch: any, data: any): void;
    effect_vol_t1_60(mod: any, ch: any, data: any): void;
    effect_vol_t1_70(mod: any, ch: any, data: any): void;
    effect_vol_t1_80(mod: any, ch: any, data: any): void;
    effect_vol_t1_90(mod: any, ch: any, data: any): void;
    effect_vol_t1_a0(mod: any, ch: any, data: any): void;
    effect_vol_t1_b0(mod: any, ch: any, data: any): void;
    effect_vol_t1_c0(mod: any, ch: any, data: any): void;
    effect_vol_t1_d0(mod: any, ch: any, data: any): void;
    effect_vol_t1_e0(mod: any, ch: any, data: any): void;
    effect_vol_t1_f0(mod: any, ch: any, data: any): void;
    effect_t0_0(mod: any, ch: any): void;
    effect_t0_1(mod: any, ch: any): void;
    effect_t0_2(mod: any, ch: any): void;
    effect_t0_3(mod: any, ch: any): void;
    effect_t0_4(mod: any, ch: any): void;
    effect_t0_5(mod: any, ch: any): void;
    effect_t0_6(mod: any, ch: any): void;
    effect_t0_7(mod: any, ch: any): void;
    effect_t0_8(mod: any, ch: any): void;
    effect_t0_9(mod: any, ch: any): void;
    effect_t0_a(mod: any, ch: any): void;
    effect_t0_b(mod: any, ch: any): void;
    effect_t0_c(mod: any, ch: any): void;
    effect_t0_d(mod: any, ch: any): void;
    effect_t0_e(mod: any, ch: any): void;
    effect_t0_f(mod: any, ch: any): void;
    effect_t0_g(mod: any, ch: any): void;
    effect_t0_h(mod: any, ch: any): void;
    effect_t0_i(mod: any, ch: any): void;
    effect_t0_j(mod: any, ch: any): void;
    effect_t0_k(mod: any, ch: any): void;
    effect_t0_l(mod: any, ch: any): void;
    effect_t0_m(mod: any, ch: any): void;
    effect_t0_n(mod: any, ch: any): void;
    effect_t0_o(mod: any, ch: any): void;
    effect_t0_p(mod: any, ch: any): void;
    effect_t0_q(mod: any, ch: any): void;
    effect_t0_r(mod: any, ch: any): void;
    effect_t0_s(mod: any, ch: any): void;
    effect_t0_t(mod: any, ch: any): void;
    effect_t0_u(mod: any, ch: any): void;
    effect_t0_v(mod: any, ch: any): void;
    effect_t0_w(mod: any, ch: any): void;
    effect_t0_x(mod: any, ch: any): void;
    effect_t0_y(mod: any, ch: any): void;
    effect_t0_z(mod: any, ch: any): void;
    effect_t0_e0(mod: any, ch: any): void;
    effect_t0_e1(mod: any, ch: any): void;
    effect_t0_e2(mod: any, ch: any): void;
    effect_t0_e3(mod: any, ch: any): void;
    effect_t0_e4(mod: any, ch: any): void;
    effect_t0_e5(mod: any, ch: any): void;
    effect_t0_e6(mod: any, ch: any): void;
    effect_t0_e7(mod: any, ch: any): void;
    effect_t0_e8(mod: any, ch: any): void;
    effect_t0_e9(mod: any, ch: any): void;
    effect_t0_ea(mod: any, ch: any): void;
    effect_t0_eb(mod: any, ch: any): void;
    effect_t0_ec(mod: any, ch: any): void;
    effect_t0_ed(mod: any, ch: any): void;
    effect_t0_ee(mod: any, ch: any): void;
    effect_t0_ef(mod: any, ch: any): void;
    effect_t1_0(mod: any, ch: any): void;
    effect_t1_1(mod: any, ch: any): void;
    effect_t1_2(mod: any, ch: any): void;
    effect_t1_3(mod: any, ch: any): void;
    effect_t1_4(mod: any, ch: any): void;
    effect_t1_5(mod: any, ch: any): void;
    effect_t1_6(mod: any, ch: any): void;
    effect_t1_7(mod: any, ch: any): void;
    effect_t1_8(mod: any, ch: any): void;
    effect_t1_9(mod: any, ch: any): void;
    effect_t1_a(mod: any, ch: any): void;
    effect_t1_b(mod: any, ch: any): void;
    effect_t1_c(mod: any, ch: any): void;
    effect_t1_d(mod: any, ch: any): void;
    effect_t1_e(mod: any, ch: any): void;
    effect_t1_f(mod: any, ch: any): void;
    effect_t1_g(mod: any, ch: any): void;
    effect_t1_h(mod: any, ch: any): void;
    effect_t1_i(mod: any, ch: any): void;
    effect_t1_j(mod: any, ch: any): void;
    effect_t1_k(mod: any, ch: any): void;
    effect_t1_l(mod: any, ch: any): void;
    effect_t1_m(mod: any, ch: any): void;
    effect_t1_n(mod: any, ch: any): void;
    effect_t1_o(mod: any, ch: any): void;
    effect_t1_p(mod: any, ch: any): void;
    effect_t1_q(mod: any, ch: any): void;
    effect_t1_r(mod: any, ch: any): void;
    effect_t1_s(mod: any, ch: any): void;
    effect_t1_t(mod: any, ch: any): void;
    effect_t1_u(mod: any, ch: any): void;
    effect_t1_v(mod: any, ch: any): void;
    effect_t1_w(mod: any, ch: any): void;
    effect_t1_x(mod: any, ch: any): void;
    effect_t1_y(mod: any, ch: any): void;
    effect_t1_z(mod: any, ch: any): void;
    effect_t1_e0(mod: any, ch: any): void;
    effect_t1_e1(mod: any, ch: any): void;
    effect_t1_e2(mod: any, ch: any): void;
    effect_t1_e3(mod: any, ch: any): void;
    effect_t1_e4(mod: any, ch: any): void;
    effect_t1_e5(mod: any, ch: any): void;
    effect_t1_e6(mod: any, ch: any): void;
    effect_t1_e7(mod: any, ch: any): void;
    effect_t1_e8(mod: any, ch: any): void;
    effect_t1_e9(mod: any, ch: any): void;
    effect_t1_ea(mod: any, ch: any): void;
    effect_t1_eb(mod: any, ch: any): void;
    effect_t1_ec(mod: any, ch: any): void;
    effect_t1_ed(mod: any, ch: any): void;
    effect_t1_ee(mod: any, ch: any): void;
    effect_t1_ef(mod: any, ch: any): void;
}
